### ISSUE TITLE
SymlinkTask  Fatal Error

### ISSUE THREAD

**Issue by bennsel** [magephp/magallanes#1]
Hello,

I´ve used the new symlink task, but there is an error. The method getAbsolutPath are not exist.

PHP Fatal error:  Call to undefined method Mage\Task\BuiltIn\Filesystem\SymlinkTask::getAbsolutPath() in /.../vendor/magephp/magallanes/Mage/Task/BuiltIn/Filesystem/SymlinkTask.php on line 65

Thanks for this great project

**Comment by cf-moriarty** [comment]
Thanks for submitting this issue. Actually, I've noticed about that mistake and already fix on my local machine. A new major version will be updated tonight.

I'm updating the documentation for this tool.

Sorry for any inconvenience you've had and my English also.

**Comment by cf-moriarty** [comment]
Please update to the latest version. And also check the new documentation here: https://magephp.github.io/

Thanks.
