### ISSUE TITLE
ProcessTimeoutException: The process "ssh...." exceeded the timeout of 120 seconds 

### ISSUE THREAD

**Issue by ivanbogomoloff** [magephp/magallanes#16]
In my .mage.yml
```
on-deploy:
 - exec: { cmd: 'long task', desc: 'desc' } 
```
where `long task` - something like npm rebuild or npm install or simple script with sleep > 120 seconds.
will give me ProcessTimeoutException.
I know that it'is not direct problem of magephp, it symfony/process dependency, but in mage bin command options not exists option like --idle-timeout or something.

Thank you!

**Comment by aschempp** [comment]
You can extend the timeout with the respective option:

```
- exec: { cmd: 'long task', desc: 'desc', timeout: 600 }
```
