### ISSUE TITLE
Base Strategy should not exclude version control directories

### ISSUE THREAD

**Issue by DavidGarciaCat** [magephp/magallanes#9]
Current `Mage\Task\BuiltIn\Deployment\Strategy\BaseStrategyTaskAbstract::getExcludes()` method is excluding `.git` directory due this array:
```
        $excludes = array(
            '.git*',
            '.svn*',
            '.mage',
            '.rsync_excludes',
            'nohup.out',
        );
```

If we cache CSS or JS files and then we update them, we need to rename the path to that file, adding a modifier like: `/path/to/my/file?modifier`

When we manage thousands of files - no matter if they are images, css or js - using a Git repository to work with colleagues is not an option to apply these modifiers manually, there is always the human factor that may cause an error or a mistake.

Twig - the tempalte engine - provides the `asset()` function that is adding this modifier automatically and, when we work with version control repositories and more colleagues, an easy way to ensure the deployment gets the last/expected updates is running this command:
`git rev-parse --short HEAD`

Given this case, we should not exclude `.git` (or any other) directory automatically, specially when we can add it on each environment configuration file (if we really don't need to deploy that folder in a given environment).

**Comment by aschempp** [comment]
I think you should add the revision locally in a pre-deployment task.

**Comment by DavidGarciaCat** [comment]
Working with Symfony I have seen many projects that are using this:
Config file `app/config/asset_version.php` with content:
```
<?php

$container->loadFromExtension(
    'framework',
    [
        'assets' => [
            'version' => trim(exec('git rev-parse --short HEAD')),
        ],
    ]
);
```

This is because Symfony+Twig are already working together to provide this revision, so exclude these folders by default may cause a problem, specially on environments that PRs and deployments are often.

**Comment by aschempp** [comment]
Why not simply dump it into the `parameters.yml` in a pre-deployment task?

**Comment by DavidGarciaCat** [comment]
That may be an option for production environments **just** if I have a single server to deploy, right?

I mean, if my environment config file contains this...

```
deployment:
  strategy: targz
  from: ./
  to: /var/www/project
  excludes:
    # Shared between releases configuration file
    - app/config/parameters.yml
```

...because I need to deploy to (let's say) `development`, `uat` and `production` servers, each one may have a different configuration, so I cannot set a new value on that parameter automatically as part of the `pre-deployment` task.

I am trying to cover all possible cases, and this is why I think we should not exclude directories by default, because given this scenario we cannot update the content of this file automativaly due these reasons:
- Locally I exclude the file because it should not be overwritten
- Remotely I cannot update the content on `post-deployment` task because I have not my `.git` folder that is the easy way to know what is the last update

**Comment by aschempp** [comment]
Sorry, you're right, the `parameters.yml` was not a good idea. It should simply be an additional file ;-)

**Comment by DavidGarciaCat** [comment]
Then we have the problem that `config.yml` file cannot read an external file because YAML files are providing an easy way to set my settings 😅 and I am not sure if is a "good idea" (or a "practical solution") update the `yml` file to `php` just to read an external resource when `config.yml` may already contain this:

```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }
    - { resource: assets_version.php }

# my other settings here
```

**Comment by aschempp** [comment]
I would dump a `asset_version.yml` file into the config directory and simply include that. Mage Tasks can easily read and write YAML because Mage uses YAML itself

**Comment by DavidGarciaCat** [comment]
So an option that you're suggesting is to update all these files:
- `config_prod.yml`
- `config_uat.yml`
- `config_dev.yml`

To include this content:
```
imports:
    - { resource: asset_version.yml } # or `asset_version.php`, depending on the environment
    - { resource: config.yml }

# environment settings here
```

And then I will need to create a new pre-deployment task to check my last local commit and set the content of `asset_version.yml` file, applying the expected format, is this right?

**Comment by aschempp** [comment]
Jup, pretty much that. It's even easier because a Mage task can easily access local **and** remote files. I just checked, there's what my task looks like. Pretty similar, though it uses the latest git tag and stores it in a different name (I don't use it for assets but just to display the platform version in the admin area).

```php
<?php

namespace Task;

use Mage\Task\AbstractTask;
use Mage\Task\ErrorWithMessageException;
use Mage\Yaml\Exception\ParseException;
use Mage\Yaml\Yaml;

class PlatformRelease extends AbstractTask
{

    /**
     * Returns the Title of the Task
     *
     * @return string
     */
    public function getName()
    {
        return 'Updating platform version in parameters.yml';
    }

    /**
     * Runs the task
     *
     * @return bool
     * @throws ErrorWithMessageException
     */
    public function run()
    {
        $version = '';

        $this->runCommandLocal("git describe", $version);

        try {
            $yaml    = new Yaml();
            $content = null;

            $this->runCommandRemote('cat app/config/parameters.yml', $content);

            $params = $yaml->parse($content);

            $params['parameters']['platform_version'] = $version;

            $this->runCommandRemote("echo " . escapeshellarg($yaml->dump($params)) . " > app/config/parameters.yml");

        } catch (ParseException $e) {
            throw new ErrorWithMessageException($e->getMessage(), $e->getCode(), $e);
        }

        return true;
    }
}
```

**Comment by DavidGarciaCat** [comment]
OK, I have tried to run that task that you pasted above, but I am not getting the expected behaviour here. For some reason, when I call this method:

```
$remote = $this->runCommandRemote('cat app/config/parameters.yml', $content);
```

And then I check the content of `$remote` and `$content` I get `false` and `NULL` respectively. Given I am working with releases, what I have done is to set these tasks:
```
tasks:
  pre-deploy:
    - filesystem/link-shared-files
    - asset-versions
```

The log says that the `ln -s` shell commands were executed with no errors, and the PHP output is:
```
Starting Magallanes
	Logging enabled: /{path-to-my-project-folder}/.mage/logs/log-20161013-153105.log

	Deploy summary
		Environment: dev
		Release ID:  20161013153105

	Starting Pre-Deployment tasks:
		Running Linking files/folders from the shared folder into the current release [built-in] ... OK
		Running Twig - Set the new Asset() version ... OK
```

I'll need to investigate about this, but if I cannot update that file I think that won't be easy to keep this version issue working with this solution.

Let me run a few tests and I'll let you know!

**Comment by aschempp** [comment]
the task needs to run as `on-deploy`, after you have linked the shared files (which I do in `on-deploy` as well). Otherwise the release folder does not exist and the file can't be found.

Here's what my deployment config looks like:

```yaml
tasks:
    pre-deploy:
        - gulp
    on-deploy:
        - filesystem/link-shared-files:
            linked_files:
                - app/config/parameters.yml: relative
            linked_folders:
                - app/logs: relative
        - composer/install: {dev: false}
        - composer/generate-autoload
        - platform-release
        - symfony2/cache-warmup: {env: prod}
        - symfony2/assets-install: {env: prod, symlink: true, relative: true}
        - maintenance-lock
    post-release:
        - symfony2/doctrine-migrate: {env: prod}
        - symfony2/cache-clear: {env: prod}
        - maintenance-unlock
```

**Comment by DavidGarciaCat** [comment]
👍 Yep, I discovered that testing the scenario that we discussed, and now the task is `on-deploy` providing the expected update. Nice chat! And thanks for the suggested update!
